Candidature:
    type: entity
    table: candidature
    indexes:
        pseufreelancer:
            columns:
                - pseufreelancer
        id_p:
            columns:
                - id_p
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estimation:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        lettreMot:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: lettre_mot
        question:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
    manyToOne:
        pseufreelancer:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pseufreelancer:
                    referencedColumnName: pseudo
            orphanRemoval: false
        idP:
            targetEntity: Projet
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_p:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
