Membre:
    type: entity
    table: membre
    indexes:
        pseudo:
            columns:
                - pseudo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        pays:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        ville:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        pseudo:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        mail:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        photo:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToMany:
        pseudoVote:
            targetEntity: Membre
            cascade: {  }
            mappedBy: pseudoVoteur
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
