Test:
    type: entity
    table: test
    indexes:
        nom:
            columns:
                - nom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        question1:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse1:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        question2:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse2:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        question3:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse3:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        question4:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse4:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        question5:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse5:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        question6:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse6:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
    manyToMany:
        idF:
            targetEntity: Freelancer
            cascade: {  }
            mappedBy: nomTest
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
