/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;


import freelancer.DAO.classes.MessageDAO;
import freelancer.entities.Message;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class EnvoyerMail extends javax.swing.JFrame {
 URL url;
 String url2,url1;
 String Filename; 
 String pseudo;
 String type;
    /**
     * Creates new form EnvoyerMail
     */
    public EnvoyerMail(String pseudo,String mail1,String mail2,String type) {
        initComponents();
        setTitle("Envoye E-mail");
    setSize(800,600);
    setResizable(false);
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
        this.type=type;
        jMailExp.setText(mail1);
        jmailDest.setText(mail2);this.setLocationRelativeTo(null);
        if("freelancer".equals(type)){
            jinter.setText("Interface Freelancer  ");
        }
        if("admin".equals(type)){
            jinter.setText("Interface admin  ");
        }
        if("jobowner".equals(type)){
            jinter.setText("Interface jobowner  ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMailExp = new java.awt.TextField();
        jPasswordAdmin = new javax.swing.JPasswordField();
        jmailDest = new javax.swing.JTextField();
        jobjet = new java.awt.TextField();
        jMessage = new java.awt.TextArea();
        jb_envoyer = new javax.swing.JButton();
        jLabelpieceJointe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf_logged = new javax.swing.JTextField();
        jinter = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jMailExp.setEditable(false);
        jMailExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailExpActionPerformed(evt);
            }
        });
        getContentPane().add(jMailExp);
        jMailExp.setBounds(250, 104, 214, 30);
        getContentPane().add(jPasswordAdmin);
        jPasswordAdmin.setBounds(250, 200, 214, 30);

        jmailDest.setEditable(false);
        jmailDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmailDestActionPerformed(evt);
            }
        });
        getContentPane().add(jmailDest);
        jmailDest.setBounds(250, 290, 214, 30);
        getContentPane().add(jobjet);
        jobjet.setBounds(250, 370, 214, 30);
        getContentPane().add(jMessage);
        jMessage.setBounds(250, 460, 260, 100);

        jb_envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_envoyerActionPerformed(evt);
            }
        });
        getContentPane().add(jb_envoyer);
        jb_envoyer.setBounds(517, 290, 240, 50);
        getContentPane().add(jLabelpieceJointe);
        jLabelpieceJointe.setBounds(105, 349, 123, 35);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(515, 400, 250, 50);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 3, 70, 50);

        tf_logged.setEditable(false);
        tf_logged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_loggedActionPerformed(evt);
            }
        });
        getContentPane().add(tf_logged);
        tf_logged.setBounds(490, 70, 77, 20);
        getContentPane().add(jinter);
        jinter.setBounds(280, 70, 206, 23);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 3, 160, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/envoyer_Mail.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMailExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailExpActionPerformed

    private void jmailDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmailDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmailDestActionPerformed

    private void jb_envoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_envoyerActionPerformed
        Pattern patternMail = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
        );
        Matcher matcherMailadmin = patternMail.matcher(jMailExp.getText());
        Matcher matcherMailDest = patternMail.matcher(jmailDest.getText());

        if (matcherMailadmin.matches()) {

            if (matcherMailDest.matches()) {

                MessageDAO messageDAO = new MessageDAO();
                Message m = new Message();
                String dest = jmailDest.getText();
                String[] to = {dest};
                m.setMailAdmin(jMailExp.getText());
                m.setMessage(jMessage.getText());
                m.setObjet(jobjet.getText());
                m.setPasswordAdmin(jPasswordAdmin.getText());
                m.setUrl(url1);
               m.setFilename(Filename);
                messageDAO.envoieMessage(m, to);
                JOptionPane.showMessageDialog(this, "votre message a été envoyé avec succès");
                if("freelancer".equals(type)){
            JFreelancerProfile j = new JFreelancerProfile(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
        if("admin".equals(type)){
            JAdminProfile j = new JAdminProfile(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
        if("jobowner".equals(type)){
            Jobowner_Profil j = new Jobowner_Profil(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
            } else {
                JOptionPane.showMessageDialog(this, "adresse mail destinataire invalide");

            }

        } else {
            JOptionPane.showMessageDialog(this, "adresse mail admin invalide");
        }
    }//GEN-LAST:event_jb_envoyerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     JFileChooser chooser = new JFileChooser();
        int option = chooser.showOpenDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            try{
                url = chooser.getSelectedFile().toURL();
                System.out.println(url);
                url1=url.toString();
                jLabelpieceJointe.setText(url1);
               
            }
            catch(MalformedURLException exception){
                System.out.println("The URL was malformed ... ");
              
            }
        }
        url2=url.toString();
        if ( url2== null)
    {
        System.out.println("null");
    }
    String newpath = url2;
    int start = newpath.lastIndexOf("/");
    if ( start == -1)
    {
      start = 0;
    }
    else
    {
      start = start + 1;
    }
    Filename = newpath.substring(start, newpath.length());

        System.out.println(Filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Jhome j=new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if("freelancer".equals(type)){
            JFreelancerProfile j = new JFreelancerProfile(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
        if("admin".equals(type)){
            JAdminProfile j = new JAdminProfile(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
        if("jobowner".equals(type)){
            Jobowner_Profil j = new Jobowner_Profil(pseudo);
            setVisible(false);
            j.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_loggedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_loggedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_loggedActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jButton2.setBorderPainted(false); 
jButton2.setContentAreaFilled(false); 
jButton2.setFocusPainted(false); 
jButton2.setOpaque(false);

jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

jButton3.setBorderPainted(false); 
jButton3.setContentAreaFilled(false); 
jButton3.setFocusPainted(false); 
jButton3.setOpaque(false);

jb_envoyer.setBorderPainted(false); 
jb_envoyer.setContentAreaFilled(false); 
jb_envoyer.setFocusPainted(false); 
jb_envoyer.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvoyerMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvoyerMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvoyerMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvoyerMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnvoyerMail v = new EnvoyerMail("tt","medamine.yahiaoui@esprit.tn","medamine.trabeslignia@esprit.tn","test");
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelpieceJointe;
    private java.awt.TextField jMailExp;
    private java.awt.TextArea jMessage;
    private javax.swing.JPasswordField jPasswordAdmin;
    private javax.swing.JButton jb_envoyer;
    private javax.swing.JLabel jinter;
    private javax.swing.JTextField jmailDest;
    private java.awt.TextField jobjet;
    private javax.swing.JTextField tf_logged;
    // End of variables declaration//GEN-END:variables
}
