/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import freelancer.dao.classes.CvFreeLancerDAO;
import freelancer.dao.classes.FreelancerDAO;
import freelancer.entities.CvFreelancer;
import freelancer.connection.DataSource;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class freelancer_cv_modifier extends javax.swing.JFrame {
     public final Connection connection;

    ArrayList <CvFreelancer> cv_CvFreelancer;
    
     String pseudo;
     


    /**
     * Creates new form cvfreelancer
     */
  
    
    
    
     public freelancer_cv_modifier(String pseudo) {
        initComponents();
         setTitle("Gestion de La CV");
setSize(800,600);
setResizable(false);this.setLocationRelativeTo(null);
         connection = DataSource.getInstance().getConnection();

        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
         Model_freelancer_moncv msg=new Model_freelancer_moncv(pseudo);
        jTfreelancercv.setModel(msg);
         try {String sql="SELECT photo_cv FROM cvfreelancer cv, membre m WHERE cv.id_cv = m.id and m.pseudo='"+pseudo+"'";
           
           Statement statement = connection
                    .createStatement();
             ResultSet rs = statement.executeQuery(sql);
               while (rs.next()){
 
                   System.out.println(rs);
                   
              byte[] imagedata=rs.getBytes("photo_cv");
                format=new ImageIcon(imagedata);
                
                
                
                jl_photo.setIcon(format);
                jl_photo.setSize(200,200);
                
                
               jl_photo.setHorizontalAlignment(jl_photo.CENTER);
         
               
                jl_photo.setVerticalAlignment(jl_photo.CENTER);
              
                }
              }
            
            
            
        
        catch(Exception e)
        {  e.printStackTrace();  }
          CvFreeLancerDAO cvDAO = new CvFreeLancerDAO();
        CvFreelancer a=new CvFreelancer();
a=cvDAO.DisplayCvFreelancer(pseudo);
        tf_certif.setText(a.getCertification_cv());
        tf_exp.setText(a.getExperience_cv());
        tf_lang.setText(a.getLangue_cv());
       tf_formation.setText(a.getFormation_cv());
    }
/*
    
    
            AfficherCompte t = new AfficherCompte(nom);

    
    */
  
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTfreelancercv = new javax.swing.JTable();
        tf_pseudo = new javax.swing.JLabel();
        jl_photo = new javax.swing.JLabel();
        tf_exp = new javax.swing.JTextField();
        tf_lang = new javax.swing.JTextField();
        tf_certif = new javax.swing.JTextField();
        tf_formation = new javax.swing.JTextField();
        j_importer = new javax.swing.JButton();
        bt_modifier1 = new javax.swing.JButton();
        Path = new javax.swing.JTextField();
        jb_capturer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTfreelancercv.setModel(new Model_freelancer_moncv(pseudo)
        );
        jTfreelancercv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTfreelancercvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTfreelancercv);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(30, 90, 140, 30);
        getContentPane().add(jl_photo);
        jl_photo.setBounds(580, 120, 200, 200);
        getContentPane().add(tf_exp);
        tf_exp.setBounds(230, 180, 220, 50);
        getContentPane().add(tf_lang);
        tf_lang.setBounds(230, 260, 220, 50);
        getContentPane().add(tf_certif);
        tf_certif.setBounds(230, 340, 220, 50);
        getContentPane().add(tf_formation);
        tf_formation.setBounds(240, 420, 220, 50);

        j_importer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_importerActionPerformed(evt);
            }
        });
        getContentPane().add(j_importer);
        j_importer.setBounds(80, 510, 110, 40);

        bt_modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifier1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_modifier1);
        bt_modifier1.setBounds(580, 350, 170, 40);
        getContentPane().add(Path);
        Path.setBounds(240, 500, 210, 50);

        jb_capturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_capturerActionPerformed(evt);
            }
        });
        getContentPane().add(jb_capturer);
        jb_capturer.setBounds(480, 510, 180, 40);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 0, 50, 50);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(663, 3, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Freelancer_modifierCV.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifier1ActionPerformed
       System.out.println("ppppppppp");
        
          Date d = new Date();
        java.sql.Date sqlDate = new java.sql.Date(d.getTime());
       CvFreelancer ad = new CvFreelancer(sqlDate,tf_exp.getText(), tf_lang.getText(),tf_certif.getText(),tf_formation.getText());
              // (String dernier_maj_cv, String experience_cv, String langue_cv, String certification_cv ) 
       CvFreeLancerDAO adDAO = new  CvFreeLancerDAO();
            adDAO.updateCvFreelancer(ad,(String)jTfreelancercv.getValueAt(0,5));
             try {
            String requete2="UPDATE cvfreelancer cv , membre m SET `photo_cv`=? WHERE cv.id_cv = m.id and m.pseudo='"+pseudo+"'";

            PreparedStatement ps = connection.prepareStatement(requete2);
            ps.setBytes(1,image_person);
            ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(FreelancerDAO.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur lors du chargement des depots " + ex.getMessage());
            System.out.println("********************!!**********exxxx************************************");

        }
            freelancer_cv_modifier a1 = new freelancer_cv_modifier(pseudo);
            setVisible(false);//Masquer la JFrame actuelle
            a1.setVisible(true);//Afficher la JFrame Résultat r1
            System.out.println("ppppppppp");
        
    }//GEN-LAST:event_bt_modifier1ActionPerformed

    private void j_importerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_importerActionPerformed

        JFileChooser chooser = new JFileChooser();

        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        Path.setText(filename);
        try
        {
            File image=new File (filename);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf =new byte[1024];
            for (int readNum;(readNum=fis.read(buf))!=-1;)

            {
                bos.write(buf,0,readNum);
            }
            image_person=bos.toByteArray();

        }
        catch(Exception e )
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_j_importerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        bt_modifier1.setBorderPainted(false); 
bt_modifier1.setContentAreaFilled(false); 
bt_modifier1.setFocusPainted(false); 
bt_modifier1.setOpaque(false);


j_importer.setBorderPainted(false); 
j_importer.setContentAreaFilled(false); 
j_importer.setFocusPainted(false); 
j_importer.setOpaque(false);


jb_capturer.setBorderPainted(false); 
jb_capturer.setContentAreaFilled(false); 
jb_capturer.setFocusPainted(false); 
jb_capturer.setOpaque(false);

jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

jButton2.setBorderPainted(false); 
jButton2.setContentAreaFilled(false); 
jButton2.setFocusPainted(false); 
jButton2.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    private void jb_capturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_capturerActionPerformed
        SnaPshot2 p= new SnaPshot2();
        p.setVisible(true);
    }//GEN-LAST:event_jb_capturerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JGestionCv j = new JGestionCv(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTfreelancercvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfreelancercvMouseClicked

        tf_exp.setText((String) jTfreelancercv.getValueAt(jTfreelancercv.getSelectedRow(),0));
        tf_lang.setText((String) jTfreelancercv.getValueAt(jTfreelancercv.getSelectedRow(),1));
        tf_certif.setText((String) jTfreelancercv.getValueAt(jTfreelancercv.getSelectedRow(),2));
        tf_formation.setText((String) jTfreelancercv.getValueAt(jTfreelancercv.getSelectedRow(),3));

    }//GEN-LAST:event_jTfreelancercvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(freelancer_cv_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(freelancer_cv_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(freelancer_cv_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(freelancer_cv_modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Path;
    private javax.swing.JButton bt_modifier1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTfreelancercv;
    private javax.swing.JButton j_importer;
    private javax.swing.JButton jb_capturer;
    private javax.swing.JLabel jl_photo;
    private javax.swing.JTextField tf_certif;
    private javax.swing.JTextField tf_exp;
    private javax.swing.JTextField tf_formation;
    private javax.swing.JTextField tf_lang;
    public javax.swing.JLabel tf_pseudo;
    // End of variables declaration//GEN-END:variables

public ImageIcon format =null;

byte[] image_person=null;


}
