/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.opencv.core.Core;

/**
 *
 * @author Amine
 */
public class JAdminProfile extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JAdminProfile
     */
    public JAdminProfile(String pseudo) {
        initComponents();
        setTitle("Menu Administrateur");
    setSize(800,600);
    setResizable(false);
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_tests = new javax.swing.JButton();
        bt_membres = new javax.swing.JButton();
        bt_reclamation = new javax.swing.JButton();
        bt_stats = new javax.swing.JButton();
        bt_msg = new javax.swing.JButton();
        bt_logout = new javax.swing.JButton();
        bt_profil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Administrateur ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 121, 14);

        tf_pseudo.setEditable(false);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 120, 123, 20);

        bt_tests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_testsActionPerformed(evt);
            }
        });
        getContentPane().add(bt_tests);
        bt_tests.setBounds(10, 270, 220, 50);

        bt_membres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_membresActionPerformed(evt);
            }
        });
        getContentPane().add(bt_membres);
        bt_membres.setBounds(280, 270, 230, 50);

        bt_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reclamationActionPerformed(evt);
            }
        });
        getContentPane().add(bt_reclamation);
        bt_reclamation.setBounds(540, 270, 240, 51);

        bt_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_statsActionPerformed(evt);
            }
        });
        getContentPane().add(bt_stats);
        bt_stats.setBounds(280, 420, 240, 50);

        bt_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_msgActionPerformed(evt);
            }
        });
        getContentPane().add(bt_msg);
        bt_msg.setBounds(10, 420, 240, 51);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(600, 0, 200, 50);

        bt_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_profilActionPerformed(evt);
            }
        });
        getContentPane().add(bt_profil);
        bt_profil.setBounds(550, 420, 230, 51);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_Profil.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_testsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_testsActionPerformed
        JGestionTest j = new JGestionTest(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_testsActionPerformed

    private void bt_membresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_membresActionPerformed
        JGestionMembre a = new JGestionMembre(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_membresActionPerformed

    private void bt_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reclamationActionPerformed
        JAfficherReclamation a = new JAfficherReclamation(pseudo);
        setVisible(false);
        a.setVisible(true);

    }//GEN-LAST:event_bt_reclamationActionPerformed

    private void bt_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_statsActionPerformed
    JStatistique j = new JStatistique(pseudo,"admin");
        setVisible(false);
        j.setVisible(true);
        
    }//GEN-LAST:event_bt_statsActionPerformed

    private void bt_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_msgActionPerformed
        JAdminMessagerie a = new JAdminMessagerie(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_msgActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_profilActionPerformed
        JAdminPerso aa=new JAdminPerso(pseudo);
        setVisible(false);
        aa.setVisible(true);
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }//GEN-LAST:event_bt_profilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

 bt_membres.setBorderPainted(false); 
bt_membres.setContentAreaFilled(false); 
bt_membres.setFocusPainted(false); 
bt_membres.setOpaque(false); 

bt_msg.setBorderPainted(false); 
bt_msg.setContentAreaFilled(false); 
bt_msg.setFocusPainted(false); 
bt_msg.setOpaque(false);

bt_profil.setBorderPainted(false); 
bt_profil.setContentAreaFilled(false); 
bt_profil.setFocusPainted(false); 
bt_profil.setOpaque(false); 

bt_reclamation.setBorderPainted(false); 
bt_reclamation.setContentAreaFilled(false); 
bt_reclamation.setFocusPainted(false); 
bt_reclamation.setOpaque(false);

bt_stats.setBorderPainted(false); 
bt_stats.setContentAreaFilled(false); 
bt_stats.setFocusPainted(false); 
bt_stats.setOpaque(false); 

bt_tests.setBorderPainted(false); 
bt_tests.setContentAreaFilled(false); 
bt_tests.setFocusPainted(false); 
bt_tests.setOpaque(false); 



    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdminProfile("hhhhh").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_membres;
    private javax.swing.JButton bt_msg;
    private javax.swing.JButton bt_profil;
    private javax.swing.JButton bt_reclamation;
    private javax.swing.JButton bt_stats;
    private javax.swing.JButton bt_tests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_pseudo;
    // End of variables declaration//GEN-END:variables
}
