/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.dao.classes.AdministrateurDAO;
import freelancer.dao.classes.ReclamationDAO;
import freelancer.entities.Administrateur;
import freelancer.entities.Reclamation;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amine
 */
public class JAfficherReclamation extends javax.swing.JFrame {
ArrayList<Reclamation> R_Reclamation;
String pseudo;
    /**
     * Creates new form JAfficherReclamation
     */
    public JAfficherReclamation(String pseudo) {
        initComponents();
        setTitle("Consultation Des Reclamations");
    setSize(800,600);
    setResizable(false);
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
         ReclamationDAO rec = new ReclamationDAO();this.setLocationRelativeTo(null);
  R_Reclamation=(ArrayList<Reclamation>) rec.DisplayAllReclamations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_supprim = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        bt_repondre = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new ModelReclamation());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 200, 594, 238);

        bt_supprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimActionPerformed(evt);
            }
        });
        getContentPane().add(bt_supprim);
        bt_supprim.setBounds(90, 510, 220, 50);
        getContentPane().add(Message);
        Message.setBounds(663, 259, 238, 32);

        bt_repondre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_repondreActionPerformed(evt);
            }
        });
        getContentPane().add(bt_repondre);
        bt_repondre.setBounds(450, 510, 220, 50);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 0, 50, 50);

        jLabel1.setText("Interface Administrateur ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 121, 14);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(100, 120, 107, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 0, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_Afficher Reclamation.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_supprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimActionPerformed
         ReclamationDAO rec = new ReclamationDAO();
  if(jTable1.getSelectedRow()==-1){
                        JOptionPane.showMessageDialog(null, "Veuillez séléctionner une raclamation !!"
                                ,"Message",JOptionPane.INFORMATION_MESSAGE);

        }
        else{
 rec.deleteReclamation((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
 JAfficherReclamation aff = new JAfficherReclamation(pseudo);
        setVisible(false);//Masquer la JFrame actuelle
        aff.setVisible(true);//Afficher la JFrame Résultat r1 
        
  }
    }//GEN-LAST:event_bt_supprimActionPerformed

    private void bt_repondreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_repondreActionPerformed
        JAdminEnvoyMessage j = new JAdminEnvoyMessage(pseudo,(String)jTable1.getValueAt(jTable1.getSelectedRow(),1));
        if(jTable1.getSelectedRow()==-1){
                        JOptionPane.showMessageDialog(null, "Veuillez séléctionner une reclamation !!"
                                ,"Message",JOptionPane.INFORMATION_MESSAGE);

        }
        else{
        setVisible(false);
        j.setVisible(true);
        }
    }//GEN-LAST:event_bt_repondreActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        JAdminProfile a = new JAdminProfile(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

bt_repondre.setBorderPainted(false); 
bt_repondre.setContentAreaFilled(false); 
bt_repondre.setFocusPainted(false); 
bt_repondre.setOpaque(false);

bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

bt_supprim.setBorderPainted(false); 
bt_supprim.setContentAreaFilled(false); 
bt_supprim.setFocusPainted(false); 
bt_supprim.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAfficherReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAfficherReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAfficherReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAfficherReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_repondre;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_supprim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_pseudo;
    // End of variables declaration//GEN-END:variables
}
