/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.TestDAO;
import freelancer.entities.Test;

/**
 *
 * @author Amine
 */
public class JAjouterTest extends javax.swing.JFrame {
String pseudo;
int id;
    /**
     * Creates new form JAjouterTest
     */
    public JAjouterTest(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        setTitle("Ajout D'un Test");
    setSize(800,600);
    setResizable(false);this.setLocationRelativeTo(null);
    }
    public JAjouterTest(String pseudo,Test t) {
        initComponents();
        this.pseudo=pseudo;
        setTitle("Ajout D'un Test");
    setSize(800,600);
    setResizable(false);
        this.setLocationRelativeTo(null);
        tf_pseudo.setText(pseudo);
        bt_valider.setText("Modifier");
        id=t.getId();
        tf_nom.setText(t.getNom());
        tf_q1.setText(t.getQuestion1());
        tf_q2.setText(t.getQuestion2());
        tf_q3.setText(t.getQuestion3());
        tf_q4.setText(t.getQuestion4());
        tf_q5.setText(t.getQuestion5());
        tf_q6.setText(t.getQuestion6());
        cb_r1.setSelectedItem(t.getReponse1());
        cb_r2.setSelectedItem(t.getReponse2());
        cb_r3.setSelectedItem(t.getReponse3());
        cb_r4.setSelectedItem(t.getReponse4());
        cb_r5.setSelectedItem(t.getReponse5());
        cb_r6.setSelectedItem(t.getReponse6());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        tf_q1 = new javax.swing.JTextField();
        tf_q2 = new javax.swing.JTextField();
        tf_q3 = new javax.swing.JTextField();
        tf_q4 = new javax.swing.JTextField();
        tf_q5 = new javax.swing.JTextField();
        tf_q6 = new javax.swing.JTextField();
        cb_r1 = new javax.swing.JComboBox();
        cb_r2 = new javax.swing.JComboBox();
        cb_r3 = new javax.swing.JComboBox();
        cb_r4 = new javax.swing.JComboBox();
        cb_r5 = new javax.swing.JComboBox();
        cb_r6 = new javax.swing.JComboBox();
        bt_valider = new javax.swing.JButton();
        tf_nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Administrateur ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 121, 14);

        tf_pseudo.setEditable(false);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 120, 123, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 13, 120, 40);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 10, 50, 40);
        getContentPane().add(tf_q1);
        tf_q1.setBounds(160, 180, 400, 30);
        getContentPane().add(tf_q2);
        tf_q2.setBounds(160, 250, 400, 30);
        getContentPane().add(tf_q3);
        tf_q3.setBounds(150, 320, 410, 30);
        getContentPane().add(tf_q4);
        tf_q4.setBounds(150, 390, 410, 40);
        getContentPane().add(tf_q5);
        tf_q5.setBounds(150, 460, 410, 40);
        getContentPane().add(tf_q6);
        tf_q6.setBounds(150, 530, 410, 40);

        cb_r1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        cb_r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_r1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb_r1);
        cb_r1.setBounds(560, 180, 43, 30);

        cb_r2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        getContentPane().add(cb_r2);
        cb_r2.setBounds(560, 250, 43, 30);

        cb_r3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        getContentPane().add(cb_r3);
        cb_r3.setBounds(560, 320, 43, 30);

        cb_r4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        getContentPane().add(cb_r4);
        cb_r4.setBounds(560, 390, 43, 40);

        cb_r5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        getContentPane().add(cb_r5);
        cb_r5.setBounds(560, 460, 43, 40);

        cb_r6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));
        getContentPane().add(cb_r6);
        cb_r6.setBounds(560, 530, 43, 40);

        bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_validerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_valider);
        bt_valider.setBounds(620, 530, 170, 30);
        getContentPane().add(tf_nom);
        tf_nom.setBounds(450, 100, 110, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_AjouterTestt.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        JGestionTest a = new JGestionTest(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_validerActionPerformed
        
        String nom=tf_nom.getText();
        String q1=tf_q1.getText();String q2=tf_q2.getText();String q3=tf_q3.getText();
        String q4=tf_q4.getText();String q5=tf_q5.getText();String q6=tf_q6.getText();
        String r1=(String)cb_r1.getSelectedItem();String r2=(String)cb_r2.getSelectedItem();
        String r3=(String)cb_r3.getSelectedItem();String r4=(String)cb_r4.getSelectedItem();
        String r5=(String)cb_r5.getSelectedItem();String r6=(String)cb_r6.getSelectedItem();
        Test t = new Test(id,nom, q1, r1, q2, r2, q3, r3, q4, r4, q5, r5, q6, r6);
        TestDAO test = new TestDAO();
        
        if(bt_valider.getText().equals("Modifier")){
            test.updateTest(t);
            JGerrerTest a = new JGerrerTest(pseudo);
            setVisible(false);
            a.setVisible(true);
        }else{
        test.insertTest(t);
        JGestionTest a = new JGestionTest(pseudo);
        setVisible(false);
        a.setVisible(true);
        }
    }//GEN-LAST:event_bt_validerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

bt_valider.setBorderPainted(false); 
bt_valider.setContentAreaFilled(false); 
bt_valider.setFocusPainted(false); 
bt_valider.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    private void cb_r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_r1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAjouterTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAjouterTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAjouterTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAjouterTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_valider;
    private javax.swing.JComboBox cb_r1;
    private javax.swing.JComboBox cb_r2;
    private javax.swing.JComboBox cb_r3;
    private javax.swing.JComboBox cb_r4;
    private javax.swing.JComboBox cb_r5;
    private javax.swing.JComboBox cb_r6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_q1;
    private javax.swing.JTextField tf_q2;
    private javax.swing.JTextField tf_q3;
    private javax.swing.JTextField tf_q4;
    private javax.swing.JTextField tf_q5;
    private javax.swing.JTextField tf_q6;
    // End of variables declaration//GEN-END:variables
}
