/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.dao.classes.ReclamationDAO;
import freelancer.entities.Reclamation;
import java.util.Date;

/**
 *
 * @author Amine
 */
public class JEnvoyReclamation extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JEnvoyReclamation
     */
    public JEnvoyReclamation(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        setTitle("Envoye D'une Reclamation");
    setSize(800,600);
    setResizable(false);this.setLocationRelativeTo(null);
    }

    JEnvoyReclamation(String pseudo, String titre) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        tf_sujet.setText(titre);
        setTitle("Envoye D'une Reclamation");
    setSize(800,600);
    setResizable(false);this.setLocationRelativeTo(null);
    }
    JEnvoyReclamation(String pseudo, String titre,int id) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        tf_sujet.setText(titre+" : "+id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_logout = new javax.swing.JButton();
        tf_pseudo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_sujet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_msg = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(660, 0, 140, 50);

        tf_pseudo.setEditable(false);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(130, 100, 90, 20);

        jLabel1.setText("Interface Freelancer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 99, 14);
        getContentPane().add(tf_sujet);
        tf_sujet.setBounds(340, 180, 290, 40);

        ta_msg.setColumns(20);
        ta_msg.setRows(5);
        jScrollPane1.setViewportView(ta_msg);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 300, 290, 100);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 410, 210, 50);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 0, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Freelancer_Envoyer Reclamation.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date d = new Date();
        java.sql.Date sqlDate = new java.sql.Date(d.getTime());
        Reclamation rec=new Reclamation(pseudo, sqlDate, tf_sujet.getText(), ta_msg.getText());
        ReclamationDAO r = new ReclamationDAO();
        r.insertReclamation(rec);
        JFreelancerProfile j = new JFreelancerProfile(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFreelancerProfile j = new JFreelancerProfile(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

jButton2.setBorderPainted(false); 
jButton2.setContentAreaFilled(false); 
jButton2.setFocusPainted(false); 
jButton2.setOpaque(false);

bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEnvoyReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEnvoyReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEnvoyReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEnvoyReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_msg;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_sujet;
    // End of variables declaration//GEN-END:variables
}
