/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.TestDAO;
import freelancer.dao.classes.MessagerieDAO;
import freelancer.entities.Test;
import javax.swing.JOptionPane;

/**
 *
 * @author Amine
 */
public class JGerrerTest extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JGerrerTest
     */
    public JGerrerTest(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        setTitle("Gestion Des Tests");
    setSize(800,600);
    setResizable(false);
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_supp = new javax.swing.JButton();
        bt_modif1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Administrateur ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 121, 14);

        tf_pseudo.setEditable(false);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 110, 123, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 10, 120, 40);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 0, 50, 50);

        jTable1.setModel(new ModelTest());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 680, 288);

        bt_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suppActionPerformed(evt);
            }
        });
        getContentPane().add(bt_supp);
        bt_supp.setBounds(100, 510, 220, 50);

        bt_modif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modif1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_modif1);
        bt_modif1.setBounds(410, 510, 220, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_GerrerTest.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        JGestionTest a = new JGestionTest(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suppActionPerformed
        TestDAO test = new TestDAO();
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner un test !!"
                    ,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            test.deleteTest((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
            JGerrerTest aff = new JGerrerTest(pseudo);
            setVisible(false);//Masquer la JFrame actuelle
            aff.setVisible(true);//Afficher la JFrame Résultat r1

        }
    }//GEN-LAST:event_bt_suppActionPerformed

    private void bt_modif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modif1ActionPerformed
        int id=(int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        String nom=(String)jTable1.getValueAt(jTable1.getSelectedRow(),1);
        String q1=(String)jTable1.getValueAt(jTable1.getSelectedRow(),2);
        String r1=(String)jTable1.getValueAt(jTable1.getSelectedRow(),3);
        String q2=(String)jTable1.getValueAt(jTable1.getSelectedRow(),4);
        String r2=(String)jTable1.getValueAt(jTable1.getSelectedRow(),5);
        String q3=(String)jTable1.getValueAt(jTable1.getSelectedRow(),6);
        String r3=(String)jTable1.getValueAt(jTable1.getSelectedRow(),7);
        String q4=(String)jTable1.getValueAt(jTable1.getSelectedRow(),8);
        String r4=(String)jTable1.getValueAt(jTable1.getSelectedRow(),9);
        String q5=(String)jTable1.getValueAt(jTable1.getSelectedRow(),10);
        String r5=(String)jTable1.getValueAt(jTable1.getSelectedRow(),11);
        String q6=(String)jTable1.getValueAt(jTable1.getSelectedRow(),12);
        String r6=(String)jTable1.getValueAt(jTable1.getSelectedRow(),13);
        Test t=new Test(id, nom, q1, r1, q2, r2, q3, r3, q4, r4, q5, r5, q6, r6);
        JAjouterTest j = new JAjouterTest(pseudo,t);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_modif1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

 bt_modif1.setBorderPainted(false); 
bt_modif1.setContentAreaFilled(false); 
bt_modif1.setFocusPainted(false); 
bt_modif1.setOpaque(false);  

 bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);  

 bt_supp.setBorderPainted(false); 
bt_supp.setContentAreaFilled(false); 
bt_supp.setFocusPainted(false); 
bt_supp.setOpaque(false);  
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGerrerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGerrerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGerrerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGerrerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_modif1;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_supp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_pseudo;
    // End of variables declaration//GEN-END:variables
}
