/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

/**
 *
 * @author Amine
 */
public class JGestionTest extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JGestionTest
     */
    public JGestionTest(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);
        setTitle("Menu Gestion Des Tests");
    setSize(800,600);
    this.setLocationRelativeTo(null);
    setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_test = new javax.swing.JButton();
        bt_gerertest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Administrateur ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 121, 14);

        tf_pseudo.setEditable(false);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 120, 120, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 0, 120, 50);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 0, 50, 50);

        bt_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_testActionPerformed(evt);
            }
        });
        getContentPane().add(bt_test);
        bt_test.setBounds(50, 310, 290, 64);

        bt_gerertest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerertestActionPerformed(evt);
            }
        });
        getContentPane().add(bt_gerertest);
        bt_gerertest.setBounds(420, 310, 320, 64);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_Gestion Test.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JAdminProfile a = new JAdminProfile(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_testActionPerformed
        JAjouterTest a = new JAjouterTest(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_testActionPerformed

    private void bt_gerertestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerertestActionPerformed
        JGerrerTest a = new JGerrerTest(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_gerertestActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         bt_gerertest.setBorderPainted(false); 
bt_gerertest.setContentAreaFilled(false); 
bt_gerertest.setFocusPainted(false); 
bt_gerertest.setOpaque(false);  

 bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);  
 
 jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

 bt_test.setBorderPainted(false); 
bt_test.setContentAreaFilled(false); 
bt_test.setFocusPainted(false); 
bt_test.setOpaque(false);  
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGestionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGestionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGestionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGestionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gerertest;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_test;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_pseudo;
    // End of variables declaration//GEN-END:variables
}
