/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.RatingDAO;
import freelancer.dao.classes.FreelancerDAO;
import freelancer.dao.classes.MembreDAO;
import freelancer.dao.classes.ReclamationDAO;
import freelancer.entities.Freelancer;
import freelancer.entities.Membre;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Amine
 */
public class JGestionFreelancer extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JGestionFreelancer
     */
    public JGestionFreelancer(String pseudo) {
        initComponents();
        setTitle("Gestion Des Freelancers");
    setSize(800,600);
    setResizable(false);
    
    
this.setLocationRelativeTo(null);

            
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
        
            
RatingDAO r = new RatingDAO();
String pseu=r.getMaxRatingFreelancer();
top.setText(top.getText()+pseu);
int rat=r.getRating(pseu);

                   
ss1.setIcon(new ImageIcon("StarRating_grey.png" ));
ss2.setIcon(new ImageIcon("StarRating_grey.png" ));
ss3.setIcon(new ImageIcon("StarRating_grey.png" ));
ss4.setIcon(new ImageIcon("StarRating_grey.png" ));
ss5.setIcon(new ImageIcon("StarRating_grey.png" ));

if (rat==5){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss5.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==4){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==3){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==2){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==1){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_logged = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        bt_cantacter = new javax.swing.JButton();
        bt_logout = new javax.swing.JButton();
        bt_mail = new javax.swing.JButton();
        bt_rechercher = new javax.swing.JButton();
        tf_rech = new javax.swing.JTextField();
        s5 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        top = new javax.swing.JLabel();
        ss1 = new javax.swing.JButton();
        ss2 = new javax.swing.JButton();
        ss3 = new javax.swing.JButton();
        ss4 = new javax.swing.JButton();
        ss5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new freelancer.gui.ModelFreelancer());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 680, 160);

        jLabel1.setText("Interface administrateur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 117, 14);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(110, 120, 112, 20);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 10, 40, 40);

        bt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_supprimer);
        bt_supprimer.setBounds(540, 500, 220, 50);

        bt_cantacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cantacterActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cantacter);
        bt_cantacter.setBounds(30, 500, 220, 50);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(680, 0, 120, 40);

        bt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mailActionPerformed(evt);
            }
        });
        getContentPane().add(bt_mail);
        bt_mail.setBounds(290, 500, 210, 50);

        bt_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(bt_rechercher);
        bt_rechercher.setBounds(510, 160, 220, 50);
        getContentPane().add(tf_rech);
        tf_rech.setBounds(380, 180, 110, 30);

        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        getContentPane().add(s5);
        s5.setBounds(20, 360, 32, 32);

        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        getContentPane().add(s4);
        s4.setBounds(20, 330, 32, 32);

        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        getContentPane().add(s3);
        s3.setBounds(20, 300, 32, 32);

        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2);
        s2.setBounds(20, 270, 32, 32);

        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(20, 240, 32, 32);

        top.setText("Top Freelancer  : ");
        getContentPane().add(top);
        top.setBounds(430, 100, 160, 14);
        getContentPane().add(ss1);
        ss1.setBounds(600, 90, 32, 32);
        getContentPane().add(ss2);
        ss2.setBounds(630, 90, 32, 32);
        getContentPane().add(ss3);
        ss3.setBounds(660, 90, 32, 32);
        getContentPane().add(ss4);
        ss4.setBounds(690, 90, 32, 32);
        getContentPane().add(ss5);
        ss5.setBounds(720, 90, 32, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_GestionFreelancer.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerActionPerformed
      
  if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner un freelancer !!"
                    ,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
      FreelancerDAO free = new FreelancerDAO();
 free.deleteFreelancerByPseudo((String)jTable1.getValueAt(jTable1.getSelectedRow(),4));
 JGestionFreelancer aff = new JGestionFreelancer(pseudo);
        setVisible(false);//Masquer la JFrame actuelle
        aff.setVisible(true);//Afficher la JFrame Résultat r1 
        
  }
    }//GEN-LAST:event_bt_supprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JGestionMembre j = new JGestionMembre(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_cantacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cantacterActionPerformed
        JAdminEnvoyMessage j = new JAdminEnvoyMessage(pseudo,(String)jTable1.getValueAt(jTable1.getSelectedRow(),4));
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_cantacterActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mailActionPerformed
        String maildest=(String)jTable1.getValueAt(jTable1.getSelectedRow(),6);
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner un freelancer !!"
                    ,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else{ 
        MembreDAO m=new MembreDAO();
        int i=0;
        i = m.getId(pseudo);
        Membre mb=new Membre();
        mb=m.findMembreById(i);
        String Mailexp=mb.getMail();
        EnvoyerMail en=new EnvoyerMail(pseudo, Mailexp, maildest, "admin");
        setVisible(false);
        en.setVisible(true);
        
        }
        
    }//GEN-LAST:event_bt_mailActionPerformed

    private void bt_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercherActionPerformed
        freelancer.gui.ModelFreelancer mj = new freelancer.gui.ModelFreelancer(tf_rech.getText());

        jTable1.setModel(mj);
    }//GEN-LAST:event_bt_rechercherActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       bt_cantacter.setBorderPainted(false); 
bt_cantacter.setContentAreaFilled(false); 
bt_cantacter.setFocusPainted(false); 
bt_cantacter.setOpaque(false);  

  bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);  

  bt_mail.setBorderPainted(false); 
bt_mail.setContentAreaFilled(false); 
bt_mail.setFocusPainted(false); 
bt_mail.setOpaque(false);  

  bt_rechercher.setBorderPainted(false); 
bt_rechercher.setContentAreaFilled(false); 
bt_rechercher.setFocusPainted(false); 
bt_rechercher.setOpaque(false);  

  bt_supprimer.setBorderPainted(false); 
bt_supprimer.setContentAreaFilled(false); 
bt_supprimer.setFocusPainted(false); 
bt_supprimer.setOpaque(false);  

 jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);  


  
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       RatingDAO ra=new RatingDAO();
int rate=ra.getRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4));

s1.setIcon(new ImageIcon("StarRating_grey.png" ));
s2.setIcon(new ImageIcon("StarRating_grey.png" ));
s3.setIcon(new ImageIcon("StarRating_grey.png" ));
s4.setIcon(new ImageIcon("StarRating_grey.png" ));
s5.setIcon(new ImageIcon("StarRating_grey.png" ));

if (rate==5){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==4){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==3){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==2){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==1){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed

    }//GEN-LAST:event_s5ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed

    }//GEN-LAST:event_s4ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed

    }//GEN-LAST:event_s3ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed

    }//GEN-LAST:event_s2ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed

    }//GEN-LAST:event_s1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGestionFreelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGestionFreelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGestionFreelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGestionFreelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cantacter;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_mail;
    private javax.swing.JButton bt_rechercher;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton ss1;
    private javax.swing.JButton ss2;
    private javax.swing.JButton ss3;
    private javax.swing.JButton ss4;
    private javax.swing.JButton ss5;
    private javax.swing.JTextField tf_logged;
    private javax.swing.JTextField tf_rech;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
