/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.RatingDAO;
import freelancer.connection.DataSource;
import freelancer.dao.classes.MembreDAO;
import freelancer.entities.Membre;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Amine
 */
public class JListeJobowner extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JListeJobowner
     */
    public JListeJobowner(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
         setTitle("Lieste Des Jobowners");
setSize(800,600);
setResizable(false);
    this.setLocationRelativeTo(null);
RatingDAO r = new RatingDAO();
String pseu=r.getMaxRatingJobowner();
top.setText(top.getText()+pseu);
int rat=r.getRating(pseu);

                   
ss1.setIcon(new ImageIcon("StarRating_grey.png" ));
ss2.setIcon(new ImageIcon("StarRating_grey.png" ));
ss3.setIcon(new ImageIcon("StarRating_grey.png" ));
ss4.setIcon(new ImageIcon("StarRating_grey.png" ));
ss5.setIcon(new ImageIcon("StarRating_grey.png" ));

if (rat==5){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss5.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==4){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==3){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==2){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rat==1){
        ss1.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_logged = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_retour = new javax.swing.JButton();
        bt_contacter = new javax.swing.JButton();
        bt_reclamation = new javax.swing.JButton();
        bt_mail = new javax.swing.JButton();
        tf_rech = new javax.swing.JTextField();
        bt_rechercher = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        top = new javax.swing.JLabel();
        ss1 = new javax.swing.JButton();
        ss2 = new javax.swing.JButton();
        ss3 = new javax.swing.JButton();
        ss4 = new javax.swing.JButton();
        ss5 = new javax.swing.JButton();
        bt_pdf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Freelancer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 99, 14);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(130, 110, 90, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 10, 120, 30);

        jTable1.setModel(new Modeljobowner());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 250, 660, 150);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(610, 10, 40, 30);

        bt_contacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contacterActionPerformed(evt);
            }
        });
        getContentPane().add(bt_contacter);
        bt_contacter.setBounds(10, 510, 240, 50);

        bt_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reclamationActionPerformed(evt);
            }
        });
        getContentPane().add(bt_reclamation);
        bt_reclamation.setBounds(540, 510, 230, 50);

        bt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mailActionPerformed(evt);
            }
        });
        getContentPane().add(bt_mail);
        bt_mail.setBounds(280, 510, 230, 50);
        getContentPane().add(tf_rech);
        tf_rech.setBounds(370, 190, 110, 30);

        bt_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(bt_rechercher);
        bt_rechercher.setBounds(570, 170, 190, 50);

        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        getContentPane().add(s3);
        s3.setBounds(40, 310, 32, 32);

        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2);
        s2.setBounds(40, 280, 32, 32);

        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(40, 250, 32, 32);

        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        getContentPane().add(s5);
        s5.setBounds(40, 370, 32, 32);

        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        getContentPane().add(s4);
        s4.setBounds(40, 340, 32, 32);

        top.setText("Top Jobowner  : ");
        getContentPane().add(top);
        top.setBounds(460, 110, 160, 14);
        getContentPane().add(ss1);
        ss1.setBounds(620, 100, 32, 32);
        getContentPane().add(ss2);
        ss2.setBounds(650, 100, 32, 32);
        getContentPane().add(ss3);
        ss3.setBounds(680, 100, 32, 32);
        getContentPane().add(ss4);
        ss4.setBounds(710, 100, 32, 32);
        getContentPane().add(ss5);
        ss5.setBounds(740, 100, 32, 32);

        bt_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/PDF.png"))); // NOI18N
        bt_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(bt_pdf);
        bt_pdf.setBounds(310, 430, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/JobOwner_ListeJobOwner.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reclamationActionPerformed
        JEnvoyReclamation j = new JEnvoyReclamation(pseudo,"JOBOWNER : "+(String)jTable1.getValueAt(jTable1.getSelectedRow(),4));
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_reclamationActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        JFreelancerProfile j = new JFreelancerProfile(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_contacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contacterActionPerformed
        JEnvoyMessage a = new JEnvoyMessage(pseudo,(String)jTable1.getValueAt(jTable1.getSelectedRow(),4));
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_contacterActionPerformed

    private void bt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mailActionPerformed
        String maildest=(String)jTable1.getValueAt(jTable1.getSelectedRow(),6);
        MembreDAO m=new MembreDAO();
        int i=0;
        i = m.getId(pseudo);
        Membre mb=new Membre();
        mb=m.findMembreById(i);
        String Mailexp=mb.getMail();
        EnvoyerMail en=new EnvoyerMail(pseudo, Mailexp, maildest, "freelancer");
        setVisible(false);
        en.setVisible(true);
    }//GEN-LAST:event_bt_mailActionPerformed

    private void bt_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercherActionPerformed
        Modeljobowner mj = new Modeljobowner(tf_rech.getText());

        jTable1.setModel(mj);
    }//GEN-LAST:event_bt_rechercherActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         bt_contacter.setBorderPainted(false); 
bt_contacter.setContentAreaFilled(false); 
bt_contacter.setFocusPainted(false); 
bt_contacter.setOpaque(false);
 bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);
 bt_rechercher.setBorderPainted(false); 
bt_rechercher.setContentAreaFilled(false); 
bt_rechercher.setFocusPainted(false); 
bt_rechercher.setOpaque(false);
 bt_mail.setBorderPainted(false); 
bt_mail.setContentAreaFilled(false); 
bt_mail.setFocusPainted(false); 
bt_mail.setOpaque(false);
bt_reclamation.setBorderPainted(false); 
bt_reclamation.setContentAreaFilled(false); 
bt_reclamation.setFocusPainted(false); 
bt_reclamation.setOpaque(false);
bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

s1.setBorderPainted(false); 
s1.setContentAreaFilled(false); 
s1.setFocusPainted(false); 
s1.setOpaque(false);

s2.setBorderPainted(false); 
s2.setContentAreaFilled(false); 
s2.setFocusPainted(false); 
s2.setOpaque(false);

s3.setBorderPainted(false); 
s3.setContentAreaFilled(false); 
s3.setFocusPainted(false); 
s3.setOpaque(false);

s4.setBorderPainted(false); 
s4.setContentAreaFilled(false); 
s4.setFocusPainted(false); 
s4.setOpaque(false);

s5.setBorderPainted(false); 
s5.setContentAreaFilled(false); 
s5.setFocusPainted(false); 
s5.setOpaque(false);


        bt_pdf.setBorderPainted(false); 
bt_pdf.setContentAreaFilled(false); 
bt_pdf.setFocusPainted(false); 
bt_pdf.setOpaque(false);

    }//GEN-LAST:event_formWindowOpened

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        System.out.println("5");
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("StarRating_yellow.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 5);
        
    }//GEN-LAST:event_s5ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        System.out.println("1");
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_grey.png" ));
        s3.setIcon(new ImageIcon("StarRating_grey.png" ));
        s4.setIcon(new ImageIcon("StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("StarRating_grey.png" ));
        
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 1);
        
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        System.out.println("2");
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_grey.png" ));
        s4.setIcon(new ImageIcon("StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 2);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        System.out.println("3");
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 3);
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        System.out.println("4");
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 4);
    }//GEN-LAST:event_s4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        RatingDAO ra=new RatingDAO();
int rate=ra.getRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4));

s1.setIcon(new ImageIcon("StarRating_grey.png" ));
s2.setIcon(new ImageIcon("StarRating_grey.png" ));
s3.setIcon(new ImageIcon("StarRating_grey.png" ));
s4.setIcon(new ImageIcon("StarRating_grey.png" ));
s5.setIcon(new ImageIcon("StarRating_grey.png" ));

if (rate==5){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==4){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==3){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==2){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("StarRating_yellow.png" ));
}

if (rate==1){
        s1.setIcon(new ImageIcon("StarRating_yellow.png" ));
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pdfActionPerformed
       try{
        Connection connection;
            connection =DataSource.getInstance().getConnection();
            System.out.println("1");
            JasperDesign Jasperdesign = JRXmlLoader.load("classic\\classic3.jrxml");
            
            
            System.out.println("2");
            JasperReport Jasperreport = JasperCompileManager.compileReport(Jasperdesign);
            System.out.println("3");
            Map parameters = new HashMap();
            parameters.put("Titre","Titre");
            System.out.println("4");
            JasperPrint jasperPrint = JasperFillManager.fillReport(Jasperreport,null,connection);
            System.out.println("5");
            JasperExportManager.exportReportToPdfFile(jasperPrint,"C:\\Users\\Amine\\Desktop\\PIdev\\Listejobowner.pdf" );
                    System.out.println("pdf généré");
        } catch (JRException ex) {
            Logger.getLogger(Superadmin_gereradministrateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JListeJobowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JListeJobowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JListeJobowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JListeJobowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_contacter;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_mail;
    private javax.swing.JButton bt_pdf;
    private javax.swing.JButton bt_rechercher;
    private javax.swing.JButton bt_reclamation;
    private javax.swing.JButton bt_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton ss1;
    private javax.swing.JButton ss2;
    private javax.swing.JButton ss3;
    private javax.swing.JButton ss4;
    private javax.swing.JButton ss5;
    private javax.swing.JTextField tf_logged;
    private javax.swing.JTextField tf_rech;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
