/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.dao.classes.MessagerieDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author sou hm
 */
public class Jobowner_Gestion_Boite_Messagerie extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form Jobowner_GestionBoiteMessagerie
     */
    public Jobowner_Gestion_Boite_Messagerie(String pseudo) {
        initComponents();
        setTitle("Gestionaire des messages");
         setSize(800,600);
         setResizable(false);
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
         ModelMessage msg=new ModelMessage(pseudo);
        jTable1.setModel(msg);this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_supprim = new javax.swing.JButton();
        bt_repondre = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_logged = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        bt_supprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimActionPerformed(evt);
            }
        });
        getContentPane().add(bt_supprim);
        bt_supprim.setBounds(90, 480, 240, 50);

        bt_repondre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_repondreActionPerformed(evt);
            }
        });
        getContentPane().add(bt_repondre);
        bt_repondre.setBounds(430, 480, 240, 50);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(550, 10, 50, 40);

        jTable1.setModel(new ModelMessage(pseudo));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 210, 680, 220);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(140, 130, 103, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(640, 10, 150, 40);

        jLabel2.setText("Interface jobowner");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 120, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Admin_BoiteMessage2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_supprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimActionPerformed
        MessagerieDAO msg = new MessagerieDAO();
        if(jTable1.getSelectedRow()==-1){
                        JOptionPane.showMessageDialog(null, "Veuillez séléctionner un message !!"
                                ,"Message",JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            msg.deleteMessage((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
            Jobowner_Gestion_Boite_Messagerie aff = new Jobowner_Gestion_Boite_Messagerie(pseudo);
            setVisible(false);//Masquer la JFrame actuelle
            aff.setVisible(true);//Afficher la JFrame Résultat 

        }
    }//GEN-LAST:event_bt_supprimActionPerformed

    private void bt_repondreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_repondreActionPerformed
      MessagerieDAO msg = new MessagerieDAO();
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner un message !!"
                    ,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        Jobowner_Envoi_Message a = new Jobowner_Envoi_Message(pseudo,(String)jTable1.getValueAt(jTable1.getSelectedRow(),1));
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_repondreActionPerformed
    }
      
    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        Jobowner_Gestion_Messagerie a = new Jobowner_Gestion_Messagerie(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

bt_repondre.setBorderPainted(false); 
bt_repondre.setContentAreaFilled(false); 
bt_repondre.setFocusPainted(false); 
bt_repondre.setOpaque(false);


bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

bt_supprim.setBorderPainted(false); 
bt_supprim.setContentAreaFilled(false); 
bt_supprim.setFocusPainted(false); 
bt_supprim.setOpaque(false);

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Boite_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Boite_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Boite_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Boite_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_repondre;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_supprim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_logged;
    // End of variables declaration//GEN-END:variables
}
