/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelancer.GUI;

import freelancer.DAO.classes.RatingDAO;
import freelancer.connection.DataSource;
import freelancer.dao.classes.MembreDAO;
import freelancer.dao.classes.MessagerieDAO;
import freelancer.entities.Membre;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Mariem
 */
public class Jobowner_Affichage_Freelancer extends javax.swing.JFrame {
String pseudo;
     public final Connection connection;

    Jobowner_Affichage_Freelancer(String pseudo) {
initComponents();
 connection = DataSource.getInstance().getConnection();
setTitle("Liste des freelancer");
         setSize(800,600);
         setResizable(false);
    this.pseudo=pseudo;
    tf_logged.setText(pseudo);
    this.setLocationRelativeTo(null);
    j_maj.setVisible(false);
                   j_cerif.setVisible(false);
                   j_exp.setVisible(false);
                   j_lang.setVisible(false);
                   j_forma.setVisible(false);
                   jl_photo.setVisible(false);
    
    maj.setVisible(false);
                   certif.setVisible(false);
                   exp.setVisible(false);
                   lang.setVisible(false);
                   forma.setVisible(false);
    
RatingDAO r = new RatingDAO();
String pseu=r.getMaxRatingFreelancer();
top.setText(top.getText()+pseu);
int rat=r.getRating(pseu);

                   
ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
ss2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
ss3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
ss4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
ss5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));

if (rat==5){
        ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rat==4){
        ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rat==3){
        ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rat==2){
        ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        ss2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rat==1){
        ss1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}
                   
    
    }

    private Jobowner_Affichage_Freelancer() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_logged = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_contact = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        bt_deconnect = new javax.swing.JButton();
        bt_cv = new javax.swing.JButton();
        bt_mail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tf_rech = new javax.swing.JTextField();
        bt_rechercher = new javax.swing.JButton();
        maj = new javax.swing.JLabel();
        exp = new javax.swing.JLabel();
        lang = new javax.swing.JLabel();
        forma = new javax.swing.JLabel();
        certif = new javax.swing.JLabel();
        j_cerif = new javax.swing.JLabel();
        j_forma = new javax.swing.JLabel();
        j_lang = new javax.swing.JLabel();
        j_exp = new javax.swing.JLabel();
        j_maj = new javax.swing.JLabel();
        s5 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        ss1 = new javax.swing.JButton();
        ss2 = new javax.swing.JButton();
        ss3 = new javax.swing.JButton();
        ss4 = new javax.swing.JButton();
        ss5 = new javax.swing.JButton();
        top = new javax.swing.JLabel();
        bt_pdf = new javax.swing.JButton();
        jl_photo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(134, 120, 100, 20);

        jTable1.setModel(new freelancer.gui.ModelFreelancer());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 770, 100);

        bt_contact.setForeground(new java.awt.Color(0, 0, 153));
        bt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contactActionPerformed(evt);
            }
        });
        getContentPane().add(bt_contact);
        bt_contact.setBounds(20, 520, 230, 50);

        bt_retour.setForeground(new java.awt.Color(0, 0, 153));
        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 0, 50, 50);

        bt_deconnect.setForeground(new java.awt.Color(0, 0, 153));
        bt_deconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deconnectActionPerformed(evt);
            }
        });
        getContentPane().add(bt_deconnect);
        bt_deconnect.setBounds(660, 0, 140, 50);
        getContentPane().add(bt_cv);
        bt_cv.setBounds(550, 520, 210, 50);

        bt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mailActionPerformed(evt);
            }
        });
        getContentPane().add(bt_mail);
        bt_mail.setBounds(300, 520, 230, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 0, 0);
        getContentPane().add(tf_rech);
        tf_rech.setBounds(400, 190, 130, 50);

        bt_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(bt_rechercher);
        bt_rechercher.setBounds(550, 190, 190, 50);

        maj.setForeground(new java.awt.Color(255, 255, 255));
        maj.setText("Dernier MAJ");
        getContentPane().add(maj);
        maj.setBounds(100, 360, 152, 23);

        exp.setForeground(new java.awt.Color(255, 255, 255));
        exp.setText("Experience");
        getContentPane().add(exp);
        exp.setBounds(100, 390, 152, 23);

        lang.setForeground(new java.awt.Color(255, 255, 255));
        lang.setText("Langue");
        getContentPane().add(lang);
        lang.setBounds(100, 420, 152, 23);

        forma.setForeground(new java.awt.Color(255, 255, 255));
        forma.setText("Formation");
        getContentPane().add(forma);
        forma.setBounds(100, 450, 152, 23);

        certif.setForeground(new java.awt.Color(255, 255, 255));
        certif.setText("Certification");
        getContentPane().add(certif);
        certif.setBounds(100, 480, 152, 23);
        getContentPane().add(j_cerif);
        j_cerif.setBounds(170, 480, 227, 23);
        getContentPane().add(j_forma);
        j_forma.setBounds(170, 450, 227, 23);
        getContentPane().add(j_lang);
        j_lang.setBounds(170, 420, 227, 23);
        getContentPane().add(j_exp);
        j_exp.setBounds(170, 390, 227, 20);
        getContentPane().add(j_maj);
        j_maj.setBounds(180, 360, 227, 23);

        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        getContentPane().add(s5);
        s5.setBounds(540, 440, 32, 32);

        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        getContentPane().add(s4);
        s4.setBounds(510, 440, 32, 32);

        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        getContentPane().add(s3);
        s3.setBounds(480, 440, 32, 32);

        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2);
        s2.setBounds(450, 440, 32, 32);

        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(420, 440, 32, 32);
        getContentPane().add(ss1);
        ss1.setBounds(570, 110, 32, 32);
        getContentPane().add(ss2);
        ss2.setBounds(600, 110, 32, 32);
        getContentPane().add(ss3);
        ss3.setBounds(630, 110, 32, 32);
        getContentPane().add(ss4);
        ss4.setBounds(660, 110, 32, 32);
        getContentPane().add(ss5);
        ss5.setBounds(690, 110, 32, 32);

        top.setForeground(new java.awt.Color(255, 255, 255));
        top.setText("Top Freelancer  : ");
        getContentPane().add(top);
        top.setBounds(480, 120, 160, 14);

        bt_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/PDF.png"))); // NOI18N
        bt_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(bt_pdf);
        bt_pdf.setBounds(420, 380, 150, 50);
        getContentPane().add(jl_photo);
        jl_photo.setBounds(620, 370, 160, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/JobOwner_AffichageFreelancer.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contactActionPerformed
MessagerieDAO msg = new MessagerieDAO();
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner un message !!"
                    ,"Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        Jobowner_Envoi_Message a = new Jobowner_Envoi_Message(pseudo,(String)jTable1.getValueAt(jTable1.getSelectedRow(),1));
        setVisible(false);
        a.setVisible(true);
    }              
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_contactActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        // TODO add your handling code here:
        
          Jobowner_Profil j=new Jobowner_Profil(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_deconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deconnectActionPerformed
        // TODO add your handling code here:
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_deconnectActionPerformed

    private void bt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mailActionPerformed
        String maildest=(String)jTable1.getValueAt(jTable1.getSelectedRow(),7);
        MembreDAO m=new MembreDAO();
        int i=0;
        i = m.getId(pseudo);
        Membre mb=new Membre();
        mb=m.findMembreById(i);
        String Mailexp=mb.getMail();
        EnvoyerMail en=new EnvoyerMail(pseudo, Mailexp, maildest, "jobowner");
        setVisible(false);
        en.setVisible(true);
    }//GEN-LAST:event_bt_mailActionPerformed

    private void bt_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercherActionPerformed
        freelancer.gui.ModelFreelancer mj = new freelancer.gui.ModelFreelancer(tf_rech.getText());

        jTable1.setModel(mj);
    }//GEN-LAST:event_bt_rechercherActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        RatingDAO ra=new RatingDAO();
int rate=ra.getRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4));

s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));

if (rate==5){
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rate==4){
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rate==3){
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rate==2){
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}

if (rate==1){
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
}
        
        
        
        String pseudof=(String) jTable1.getValueAt(jTable1.getSelectedRow(),5);
        
        try {String sql="SELECT * FROM cvfreelancer cv, membre m WHERE cv.id_cv = m.id and m.pseudo='"+pseudof+"'";
            Statement statement = connection
                    .createStatement();
             ResultSet rs = statement.executeQuery(sql);
               if (rs.next()){
                   maj.setVisible(true);
                   certif.setVisible(true);
                   exp.setVisible(true);
                   lang.setVisible(true);
                   forma.setVisible(true);
                   j_maj.setVisible(true);
                   j_cerif.setVisible(true);
                   j_exp.setVisible(true);
                   j_lang.setVisible(true);
                   j_forma.setVisible(true);
                   jl_photo.setVisible(true);
                   j_maj.setText(rs.getString(2));
                   j_exp.setText(rs.getString(3));
                   j_lang.setText(rs.getString(4));
                   j_cerif.setText(rs.getString(5));
                   j_forma.setText(rs.getString(6));
                   
                   System.out.println(rs);
                   
              byte[] imagedata=rs.getBytes("photo_cv");
                format=new ImageIcon(imagedata);
                jl_photo.setIcon(format);
                jl_photo.setSize(200,200);
                
               jl_photo.setHorizontalAlignment(jl_photo.CENTER);
                jl_photo.setVerticalAlignment(jl_photo.CENTER);
                }
               else{
                   maj.setVisible(false);
                   certif.setVisible(false);
                   exp.setVisible(false);
                   lang.setVisible(false);
                   forma.setVisible(false);
                   j_maj.setVisible(false);
                   j_cerif.setVisible(false);
                   j_exp.setVisible(false);
                   j_lang.setVisible(false);
                   j_forma.setVisible(false);
                   jl_photo.setVisible(false);
               }
             }

        
        catch(Exception e)
        {  e.printStackTrace();  }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        System.out.println("5");
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 5);

    }//GEN-LAST:event_s5ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        System.out.println("4");
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 4);
    }//GEN-LAST:event_s4ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        System.out.println("3");
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 3);
    }//GEN-LAST:event_s3ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        System.out.println("2");
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 2);
    }//GEN-LAST:event_s2ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        System.out.println("1");
        s1.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_yellow.png" ));
        s2.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s3.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s4.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));
        s5.setIcon(new ImageIcon("C:\\Users\\Amine\\Desktop\\StarRating_grey.png" ));

        RatingDAO r = new RatingDAO();
        r.CalculRating((String)jTable1.getValueAt(jTable1.getSelectedRow(),4),pseudo, 1);

    }//GEN-LAST:event_s1ActionPerformed

    private void bt_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pdfActionPerformed
     try{
        Connection connection;
            connection =DataSource.getInstance().getConnection();
            System.out.println("1");
            JasperDesign Jasperdesign = JRXmlLoader.load("classic\\classic2.jrxml");
            
            
            System.out.println("2");
            JasperReport Jasperreport = JasperCompileManager.compileReport(Jasperdesign);
            System.out.println("3");
            Map parameters = new HashMap();
            parameters.put("Titre","Titre");
            System.out.println("4");
            JasperPrint jasperPrint = JasperFillManager.fillReport(Jasperreport,null,connection);
            System.out.println("5");
            JasperExportManager.exportReportToPdfFile(jasperPrint,"C:\\Users\\Amine\\Desktop\\PIdev\\ListeFreelancer.pdf" );
                    System.out.println("pdf généré");
        } catch (JRException ex) {
            Logger.getLogger(Superadmin_gereradministrateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_pdfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
bt_contact.setBorderPainted(false); 
bt_contact.setContentAreaFilled(false); 
bt_contact.setFocusPainted(false); 
bt_contact.setOpaque(false);

bt_cv.setBorderPainted(false); 
bt_cv.setContentAreaFilled(false); 
bt_cv.setFocusPainted(false); 
bt_cv.setOpaque(false);

bt_deconnect.setBorderPainted(false); 
bt_deconnect.setContentAreaFilled(false); 
bt_deconnect.setFocusPainted(false); 
bt_deconnect.setOpaque(false);

bt_mail.setBorderPainted(false); 
bt_mail.setContentAreaFilled(false); 
bt_mail.setFocusPainted(false); 
bt_mail.setOpaque(false);

bt_pdf.setBorderPainted(false); 
bt_pdf.setContentAreaFilled(false); 
bt_pdf.setFocusPainted(false); 
bt_pdf.setOpaque(false);

bt_rechercher.setBorderPainted(false); 
bt_rechercher.setContentAreaFilled(false); 
bt_rechercher.setFocusPainted(false); 
bt_rechercher.setOpaque(false);

bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Affichage_Freelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Affichage_Freelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Affichage_Freelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Affichage_Freelancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_contact;
    private javax.swing.JButton bt_cv;
    private javax.swing.JButton bt_deconnect;
    private javax.swing.JButton bt_mail;
    private javax.swing.JButton bt_pdf;
    private javax.swing.JButton bt_rechercher;
    private javax.swing.JButton bt_retour;
    private javax.swing.JLabel certif;
    private javax.swing.JLabel exp;
    private javax.swing.JLabel forma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel j_cerif;
    private javax.swing.JLabel j_exp;
    private javax.swing.JLabel j_forma;
    private javax.swing.JLabel j_lang;
    private javax.swing.JLabel j_maj;
    private javax.swing.JLabel jl_photo;
    private javax.swing.JLabel lang;
    private javax.swing.JLabel maj;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton ss1;
    private javax.swing.JButton ss2;
    private javax.swing.JButton ss3;
    private javax.swing.JButton ss4;
    private javax.swing.JButton ss5;
    private javax.swing.JTextField tf_logged;
    private javax.swing.JTextField tf_rech;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
public ImageIcon format =null;

byte[] image_person=null;

}
