/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freelancer.GUI;

import freelancer.connection.DataSource;
import freelancer.dao.classes.ProjetDAO;
import freelancer.entities.Projet;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariem
 */
public class Jobowner_Affichage_Projets extends javax.swing.JFrame {
    String pseudo;
    public final Connection connection;

    /**
     * Creates new form JAffichageProjets
     */


    Jobowner_Affichage_Projets(String pseudo) {
        initComponents();
        connection = DataSource.getInstance().getConnection();
        setTitle("List des Projets");
         setSize(800,600);
         setResizable(false);
        this.pseudo=pseudo;
      tf_logged.setText(pseudo); 
      ModelProjet pp = new ModelProjet(pseudo);
      jTable1.setModel(pp);
      this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_logged = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bt_supp = new javax.swing.JButton();
        bt_modif = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        bt_ajouter = new javax.swing.JButton();
        tf_duree = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_desc = new javax.swing.JTextArea();
        tf_titre = new javax.swing.JTextField();
        tf_categorie = new javax.swing.JTextField();
        jl_photo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new ModelProjet(pseudo));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 730, 156);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(130, 120, 75, 20);

        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 0, 130, 50);

        bt_supp.setForeground(new java.awt.Color(0, 0, 153));
        bt_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suppActionPerformed(evt);
            }
        });
        getContentPane().add(bt_supp);
        bt_supp.setBounds(280, 520, 220, 50);

        bt_modif.setForeground(new java.awt.Color(0, 0, 153));
        bt_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modifMouseClicked(evt);
            }
        });
        bt_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifActionPerformed(evt);
            }
        });
        getContentPane().add(bt_modif);
        bt_modif.setBounds(530, 510, 230, 50);

        bt_retour.setForeground(new java.awt.Color(0, 0, 153));
        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 0, 50, 50);

        bt_ajouter.setForeground(new java.awt.Color(0, 0, 153));
        bt_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ajouter);
        bt_ajouter.setBounds(30, 520, 220, 50);
        getContentPane().add(tf_duree);
        tf_duree.setBounds(590, 350, 190, 40);

        ta_desc.setColumns(20);
        ta_desc.setRows(5);
        jScrollPane2.setViewportView(ta_desc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(590, 420, 190, 80);
        getContentPane().add(tf_titre);
        tf_titre.setBounds(250, 350, 160, 50);
        getContentPane().add(tf_categorie);
        tf_categorie.setBounds(250, 430, 160, 40);
        getContentPane().add(jl_photo);
        jl_photo.setBounds(350, 40, 200, 200);

        jLabel2.setText("Interface jobowner");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 100, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/JobOwner_AffichageProjet.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 800, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
      
        // TODO add your handling code here:
         Jobowner_Profil j = new Jobowner_Profil(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifActionPerformed
        // TODO add your handling code here:
       int i =(int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
       Date d =new Date();
   java.sql.Date date=new java.sql.Date(d.getTime());
          Projet pro = new Projet(i,date,tf_titre.getText(), tf_categorie.getText(), tf_duree.getText(),
                ta_desc.getText(),pseudo);
      
        ProjetDAO job=new ProjetDAO();
        job.updateProjet(pro, i);
         JOptionPane.showMessageDialog(null, "Modification réussie","Message",JOptionPane.INFORMATION_MESSAGE);
        Jobowner_Affichage_Projets jj = new Jobowner_Affichage_Projets (pseudo);
        setVisible(false);
        jj.setVisible(true);
        
    }//GEN-LAST:event_bt_modifActionPerformed

    private void bt_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suppActionPerformed
        // TODO add your handling code here:
        ProjetDAO pro = new  ProjetDAO();
 if(jTable1.getSelectedRow()==-1){
  }
 else{
 pro.deleteProjet((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
 Jobowner_Affichage_Projets aff = new Jobowner_Affichage_Projets(pseudo);
        setVisible(false);//Masquer la JFrame actuelle
        aff.setVisible(true);//Afficher la JFrame Résultat r1
 }
    }//GEN-LAST:event_bt_suppActionPerformed

    private void bt_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajouterActionPerformed
        // TODO add your handling code here:
         Jobowner_Ajouter_Projet j = new Jobowner_Ajouter_Projet(pseudo);
        setVisible(false);
        j.setVisible(true);
        
    }//GEN-LAST:event_bt_ajouterActionPerformed

    private void bt_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modifMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bt_modifMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         tf_titre.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(),1));
        tf_categorie.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(),2));
      tf_duree.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(),3));
       ta_desc.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(),4));
       
        try {
            ProjetDAO proj=new ProjetDAO();
            int i=proj.getIdProjet(tf_titre.getText(), tf_categorie.getText(), tf_duree.getText(), 
                          ta_desc.getText(), pseudo);
            String sql="SELECT photo_p FROM projet WHERE id='"+i+"'";
            Statement statement = connection
                    .createStatement();
             ResultSet rs = statement.executeQuery(sql);
               while (rs.next()){
 

              //  InputStream in = rs.getBinaryStream("photo_cv");
             // byte[] in=rs.getBytes("photo_cv");
             // BufferedImage im = ImageIO.read(new ByteArrayInputStream(in));
                   System.out.println(rs);
                   
              byte[] imagedata=rs.getBytes("photo_p");
                format=new ImageIcon(imagedata);
                //ImageIcon icon = new ImageIcon(im);
                
                
                
                jl_photo.setIcon(format);
                jl_photo.setSize(200,200);
                
       // jl_photo.setLocation(200,200);
                
               jl_photo.setHorizontalAlignment(jl_photo.CENTER);
             //  jl_photo.setSize(null);
         
               
                jl_photo.setVerticalAlignment(jl_photo.CENTER);
                
                // getSubimage(int x, int y, int w, int h)
                /*
                
                 /* JFileChooser chooser = new JFileChooser();

        if(chooser.showOpenDialog(Photo1)== JFileChooser.APPROVE_OPTION){

            java.io.File f = chooser.getSelectedFile();
            Photo1.setIcon(new ImageIcon(f.toString()) );
            Photo1.setHorizontalAlignment(Photo1.CENTER);
           // File ff = chooser.getSelectedFile();
           // PathImage = ff.getAbsolutePath();

            Image Image1 = Toolkit.getDefaultToolkit().getImage(PathImage);
            ImageIcon icon = new ImageIcon(Image1.getScaledInstance(250, 250, Image.SCALE_FAST));
            Photo1.setIcon(icon);
            Photo1.repaint();
        
        */
                
                
                
                
                
                
                
                
                }
            
            
            
             }
            
            
            
        
        catch(Exception e)
        {  e.printStackTrace();  }
       
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

bt_ajouter.setBorderPainted(false); 
bt_ajouter.setContentAreaFilled(false); 
bt_ajouter.setFocusPainted(false); 
bt_ajouter.setOpaque(false);

bt_modif.setBorderPainted(false); 
bt_modif.setContentAreaFilled(false); 
bt_modif.setFocusPainted(false); 
bt_modif.setOpaque(false);

bt_supp.setBorderPainted(false); 
bt_supp.setContentAreaFilled(false); 
bt_supp.setFocusPainted(false); 
bt_supp.setOpaque(false);

jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Affichage_Projets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ajouter;
    private javax.swing.JButton bt_modif;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_supp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jl_photo;
    private javax.swing.JTextArea ta_desc;
    private javax.swing.JTextField tf_categorie;
    private javax.swing.JTextField tf_duree;
    private javax.swing.JTextField tf_logged;
    private javax.swing.JTextField tf_titre;
    // End of variables declaration//GEN-END:variables
public ImageIcon format =null;

byte[] image_person=null;
}
