/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.connection.DataSource;
import freelancer.dao.classes.JobownerDAO;
import freelancer.dao.classes.MembreDAO;
import freelancer.dao.classes.ProjetDAO;
import freelancer.entities.Jobowner;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sou hm
 */
public class Jobowner_Gestion_Profil extends javax.swing.JFrame {
String pseudo;
int id;
    public final Connection connection;

    /**
     * Creates new form Jobowner_GestionProfil
     */
    public Jobowner_Gestion_Profil(String pseudo) {
        initComponents();
        setTitle("Gestion profil");
         setSize(800,600);
         setResizable(false);
                 connection = DataSource.getInstance().getConnection();
this.setLocationRelativeTo(null);
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
        JobownerDAO job = new JobownerDAO();
        Jobowner j=new Jobowner();
        j=job.findJobownerByPseudo(pseudo);
        tf_nom.setText(j.getNom());
        tf_prenom.setText(j.getPrenom());
        tf_pays.setText(j.getPays());
        tf_ville.setText(j.getVille());
        tf_pseudo.setText(j.getPseudo());
        tf_password.setText(j.getPassword());
        tf_mail.setText(j.getMail());
        tf_societe.setText(j.getSociete());
        id=j.getId();
        
         
        try {
            MembreDAO m=new MembreDAO();
            String sql="SELECT photo FROM membre WHERE id='"+id+"'";
            Statement statement = connection
                    .createStatement();
             ResultSet rs = statement.executeQuery(sql);
               while (rs.next()){
                System.out.println(rs);
                   
              byte[] imagedata=rs.getBytes("photo");
                format=new ImageIcon(imagedata);
                jl_photo.setIcon(format);
                jl_photo.setSize(200,200);
             jl_photo.setHorizontalAlignment(jl_photo.CENTER);
              jl_photo.setVerticalAlignment(jl_photo.CENTER);
               }} 
        catch(Exception e)
        {  e.printStackTrace();  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_pseudo = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        tf_ville = new javax.swing.JTextField();
        bt_valider = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        jl_photo = new javax.swing.JLabel();
        tf_societe = new javax.swing.JTextField();
        tf_nom = new javax.swing.JTextField();
        tf_prenom = new javax.swing.JTextField();
        tf_pays = new javax.swing.JTextField();
        tf_logged = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(490, 170, 190, 40);
        getContentPane().add(tf_mail);
        tf_mail.setBounds(490, 360, 190, 40);

        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(tf_password);
        tf_password.setBounds(490, 270, 190, 40);
        getContentPane().add(tf_ville);
        tf_ville.setBounds(160, 450, 170, 40);

        bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_validerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_valider);
        bt_valider.setBounds(550, 520, 200, 50);

        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_annuler);
        bt_annuler.setBounds(600, 0, 50, 50);
        getContentPane().add(jl_photo);
        jl_photo.setBounds(590, 70, 200, 200);

        tf_societe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_societeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_societe);
        tf_societe.setBounds(490, 450, 190, 40);
        getContentPane().add(tf_nom);
        tf_nom.setBounds(160, 180, 170, 40);
        getContentPane().add(tf_prenom);
        tf_prenom.setBounds(160, 270, 170, 40);
        getContentPane().add(tf_pays);
        tf_pays.setBounds(160, 360, 170, 40);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(50, 100, 141, 20);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(663, 0, 130, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/JobOwner_GestionProfil.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_validerActionPerformed
        Jobowner jo = new Jobowner(tf_nom.getText(), tf_prenom.getText(), tf_pays.getText(),
                tf_ville.getText(),tf_pseudo.getText(), tf_password.getText(), tf_mail.getText(),tf_societe.getText());
        System.out.println("----"+tf_nom.getText());
        JobownerDAO job=new JobownerDAO();
        job.updateJobownerDAO(jo,id);
         JOptionPane.showMessageDialog(null, "Modification réusite","Message",JOptionPane.INFORMATION_MESSAGE);
        Jobowner_Profil jj = new Jobowner_Profil(tf_pseudo.getText());
        setVisible(false);
        jj.setVisible(true);
    }//GEN-LAST:event_bt_validerActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        Jobowner_Profil j=new Jobowner_Profil(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void tf_societeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_societeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_societeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

bt_annuler.setBorderPainted(false); 
bt_annuler.setContentAreaFilled(false); 
bt_annuler.setFocusPainted(false); 
bt_annuler.setOpaque(false);

bt_valider.setBorderPainted(false); 
bt_valider.setContentAreaFilled(false); 
bt_valider.setFocusPainted(false); 
bt_valider.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_valider;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jl_photo;
    private javax.swing.JTextField tf_logged;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_pays;
    private javax.swing.JTextField tf_prenom;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_societe;
    private javax.swing.JTextField tf_ville;
    // End of variables declaration//GEN-END:variables

public ImageIcon format =null;

byte[] image_person=null;

}
