/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

/**
 *
 * @author sou hm
 */
public class Jobowner_Gestion_Messagerie extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form Jobowner_GestionMessagerie
     */
    public Jobowner_Gestion_Messagerie(String pseudo) {
        initComponents();
        setTitle("Gestion des Message");
         setSize(800,600);
         setResizable(false);
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_logged = new javax.swing.JTextField();
        bt_deconnecter = new javax.swing.JButton();
        bt_envoi = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        bt_gestion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(150, 130, 103, 20);

        bt_deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(bt_deconnecter);
        bt_deconnecter.setBounds(640, 10, 150, 40);

        bt_envoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_envoiActionPerformed(evt);
            }
        });
        getContentPane().add(bt_envoi);
        bt_envoi.setBounds(50, 360, 270, 61);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(550, 0, 50, 60);

        bt_gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gestionActionPerformed(evt);
            }
        });
        getContentPane().add(bt_gestion);
        bt_gestion.setBounds(430, 360, 310, 61);

        jLabel2.setText("Interface jobowner");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 130, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/AdminMessagerie.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deconnecterActionPerformed
        Jhome au = new Jhome();
        setVisible(false);
        au.setVisible(true);
    }//GEN-LAST:event_bt_deconnecterActionPerformed

    private void bt_gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gestionActionPerformed
        Jobowner_Gestion_Boite_Messagerie j = new Jobowner_Gestion_Boite_Messagerie(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_gestionActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        Jobowner_Profil b = new Jobowner_Profil(pseudo);
        setVisible(false);
        b.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void bt_envoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_envoiActionPerformed
        Jobowner_Envoi_Message a = new Jobowner_Envoi_Message(pseudo);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_envoiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 bt_deconnecter.setBorderPainted(false); 
bt_deconnecter.setContentAreaFilled(false); 
bt_deconnecter.setFocusPainted(false); 
bt_deconnecter.setOpaque(false);

bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);

bt_gestion.setBorderPainted(false); 
bt_gestion.setContentAreaFilled(false); 
bt_gestion.setFocusPainted(false); 
bt_gestion.setOpaque(false);

bt_envoi.setBorderPainted(false); 
bt_envoi.setContentAreaFilled(false); 
bt_envoi.setFocusPainted(false); 
bt_envoi.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jobowner_Gestion_Messagerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deconnecter;
    private javax.swing.JButton bt_envoi;
    private javax.swing.JButton bt_gestion;
    private javax.swing.JButton bt_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_logged;
    // End of variables declaration//GEN-END:variables
}
