/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.TestDAO;
import freelancer.dao.classes.MembreDAO;
import freelancer.entities.Test;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amine
 */
public class JPasserTest extends javax.swing.JFrame {
String pseudo;
    /**
     * Creates new form JPasserTest
     */
    public JPasserTest(String pseudo) {
        initComponents();
        this.pseudo=pseudo;
        tf_logged.setText(pseudo);
         setTitle("Passer Un Test");
setSize(800,620);
setResizable(false);
this.setLocationRelativeTo(null);
        cb.addItem("");
        la1.setVisible(false);la2.setVisible(false);la3.setVisible(false);
        la4.setVisible(false);la5.setVisible(false);la6.setVisible(false);
        r1.setVisible(false);r2.setVisible(false);r3.setVisible(false);
        r4.setVisible(false);r5.setVisible(false);r6.setVisible(false);
        btV.setVisible(false);
        
        List<Test> listtest = new ArrayList<Test>();
        TestDAO test=new TestDAO();
        listtest=test.DisplayAllTests();
        for (Test test1 : listtest) {
            cb.addItem(test1.getNom());
        }
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_logged = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        cb = new javax.swing.JComboBox();
        bt_retour = new javax.swing.JButton();
        btV = new javax.swing.JButton();
        la1 = new javax.swing.JLabel();
        la2 = new javax.swing.JLabel();
        la3 = new javax.swing.JLabel();
        la4 = new javax.swing.JLabel();
        la5 = new javax.swing.JLabel();
        la6 = new javax.swing.JLabel();
        r1 = new javax.swing.JComboBox();
        r2 = new javax.swing.JComboBox();
        r3 = new javax.swing.JComboBox();
        r4 = new javax.swing.JComboBox();
        r5 = new javax.swing.JComboBox();
        r6 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Interface Freelancer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 99, 14);

        tf_logged.setEditable(false);
        getContentPane().add(tf_logged);
        tf_logged.setBounds(140, 100, 80, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 0, 130, 50);

        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(420, 170, 80, 30);

        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });
        getContentPane().add(bt_retour);
        bt_retour.setBounds(600, 0, 50, 50);

        btV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVActionPerformed(evt);
            }
        });
        getContentPane().add(btV);
        btV.setBounds(590, 510, 190, 50);

        la1.setText("jLabel3");
        getContentPane().add(la1);
        la1.setBounds(90, 240, 420, 40);

        la2.setText("jLabel4");
        getContentPane().add(la2);
        la2.setBounds(90, 300, 420, 40);

        la3.setText("jLabel5");
        getContentPane().add(la3);
        la3.setBounds(90, 360, 420, 40);

        la4.setText("jLabel6");
        getContentPane().add(la4);
        la4.setBounds(90, 420, 420, 40);

        la5.setText("jLabel7");
        getContentPane().add(la5);
        la5.setBounds(90, 480, 420, 40);

        la6.setText("jLabel8");
        getContentPane().add(la6);
        la6.setBounds(90, 540, 420, 40);

        r1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r1);
        r1.setBounds(510, 240, 60, 40);

        r2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r2);
        r2.setBounds(510, 300, 60, 40);

        r3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r3);
        r3.setBounds(510, 360, 60, 40);

        r4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r4);
        r4.setBounds(510, 420, 60, 40);

        r5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r5);
        r5.setBounds(510, 480, 60, 40);

        r6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "oui", "non" }));
        getContentPane().add(r6);
        r6.setBounds(510, 540, 60, 40);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 367, 187, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/Freelancer_Passer Test.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        if(cb.getSelectedItem()!=""){
        la1.setVisible(true);la2.setVisible(true);la3.setVisible(true);
        la4.setVisible(true);la5.setVisible(true);la6.setVisible(true);
        r1.setVisible(true);r2.setVisible(true);r3.setVisible(true);
        r4.setVisible(true);r5.setVisible(true);r6.setVisible(true);
        btV.setVisible(true);
        TestDAO tt=new TestDAO();
        Test tes=new Test();
        tes=tt.GetTest((String)cb.getSelectedItem());
        la1.setText(tes.getQuestion1());la2.setText(tes.getQuestion2());la3.setText(tes.getQuestion3());
        la4.setText(tes.getQuestion4());la5.setText(tes.getQuestion5());la6.setText(tes.getQuestion6());
        }
    }//GEN-LAST:event_cbItemStateChanged

    private void btVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVActionPerformed
        TestDAO test=new TestDAO();
        MembreDAO m = new MembreDAO();
        int idd=0;
        idd=m.getId(pseudo);
        int note=test.GetNoteTest((String)cb.getSelectedItem(), (String)r1.getSelectedItem(),(String) r2.getSelectedItem()
                ,(String) r3.getSelectedItem(),(String)r4.getSelectedItem(), (String)r5.getSelectedItem(), 
                (String)r6.getSelectedItem(),idd);
        
        
    }//GEN-LAST:event_btVActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        JFreelancerTest j = new JFreelancerTest(pseudo);
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

  bt_retour.setBorderPainted(false); 
bt_retour.setContentAreaFilled(false); 
bt_retour.setFocusPainted(false); 
bt_retour.setOpaque(false);
  
       btV.setBorderPainted(false); 
 btV.setContentAreaFilled(false); 
 btV.setFocusPainted(false); 
 btV.setOpaque(false);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPasserTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPasserTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPasserTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPasserTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btV;
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_retour;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel la1;
    private javax.swing.JLabel la2;
    private javax.swing.JLabel la3;
    private javax.swing.JLabel la4;
    private javax.swing.JLabel la5;
    private javax.swing.JLabel la6;
    private javax.swing.JComboBox r1;
    private javax.swing.JComboBox r2;
    private javax.swing.JComboBox r3;
    private javax.swing.JComboBox r4;
    private javax.swing.JComboBox r5;
    private javax.swing.JComboBox r6;
    private javax.swing.JTextField tf_logged;
    // End of variables declaration//GEN-END:variables
}
