/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.MessageDAO;
import freelancer.dao.classes.AdministrateurDAO;
import freelancer.dao.classes.MembreDAO;
import freelancer.entities.Administrateur;
import freelancer.entities.Message;
import javax.swing.JOptionPane;

/**
 *
 * @author Amine
 */
public class Motdepasseoublier extends javax.swing.JFrame {
String Filename;
String url1;
    /**
     * Creates new form Motdepasseoublier
     */
    public Motdepasseoublier() {
        initComponents();
        initComponents();
        setTitle("Recuperer mots de passe");
setSize(800,600);
setResizable(false);

      jMailAdmin2.setVisible(false);
      jPasswordAdmin.setVisible(false);
      this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bt_recup = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMailAdmin2 = new javax.swing.JTextField();
        jPasswordAdmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 250, 290, 60);

        bt_recup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_recupActionPerformed(evt);
            }
        });
        getContentPane().add(bt_recup);
        bt_recup.setBounds(310, 420, 230, 60);

        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        getContentPane().add(bt_back);
        bt_back.setBounds(600, 0, 190, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/mot_de_passe_perdu.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 790, 590);

        jMailAdmin2.setText("freelancer.pidev@gmail.com");
        jMailAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailAdmin2ActionPerformed(evt);
            }
        });
        getContentPane().add(jMailAdmin2);
        jMailAdmin2.setBounds(472, 580, 159, 20);

        jPasswordAdmin.setText("freelancer123freelancer"); // NOI18N
        jPasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordAdmin);
        jPasswordAdmin.setBounds(641, 580, 159, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_recupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_recupActionPerformed

        MessageDAO messageDAO = new MessageDAO();
        Message m = new Message();
        String dest =jTextField1.getText();
        String[] to = {dest};
        //m.setMailAdmin("elusive.di.elusive@gmail.com");
        m.setMailAdmin(jMailAdmin2.getText());
        MembreDAO ad = new MembreDAO();
        m.setMessage("Détails de votre compte Freelancer\n Quelqu'un utilisant le courriel ("+jTextField1.getText()+")\na demandé a voir le mot de passe et le login de ce compte\nUtilisateur:"+ad.findMembreBymail(dest).getPseudo()+"\nmot de passe :"+ad.findMembreBymail(dest).getPassword());
        System.out.println();
        m.setObjet("Recuperation de compte");
        m.setFilename(Filename);
        m.setUrl(url1);
       // m.setPasswordAdmin("elusivedielusive");
        m.setPasswordAdmin(jPasswordAdmin.getText());
        messageDAO.envoieMessage(m, to);
        JOptionPane.showMessageDialog(this, "votre message a été envoyé avec succès");
    }//GEN-LAST:event_bt_recupActionPerformed

    private void jMailAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailAdmin2ActionPerformed

    private void jPasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordAdminActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        Jhome j = new Jhome();
        setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   bt_back.setBorderPainted(false); 
   bt_back.setContentAreaFilled(false); 
bt_back.setFocusPainted(false); 
bt_back.setOpaque(false);

bt_recup.setBorderPainted(false); 
bt_recup.setContentAreaFilled(false); 
bt_recup.setFocusPainted(false); 
bt_recup.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Motdepasseoublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Motdepasseoublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Motdepasseoublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Motdepasseoublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Motdepasseoublier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_recup;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jMailAdmin2;
    private javax.swing.JPasswordField jPasswordAdmin;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
