/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author hp
 */
public class SplashScreen extends javax.swing.JFrame {
private Timer t =null;
private int count =0;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
         setTitle("Gestion des statestique");
setSize(800,600);
setResizable(false);
 this.setLocationRelativeTo(null);
        t= new Timer (100,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                count+=3;
                 
                jProgressBar.setBackground(Color.red);
jProgressBar.setForeground(Color.red);
//UIManager.put("jProgressBar.background", Color.blue); //colour of the background
 //   UIManager.put("jProgressBar.foreground", Color.blue);  //colour of progress bar
  //  UIManager.put("jProgressBar.selectionBackground",Color.blue);  //colour of percentage counter on black background
  //  UIManager.put("jProgressBar.selectionForeground",Color.blue);
 //    UIManager.put("jProgressBar.selectionForeground", new ColorUIResource(Color.blue));
//UIManager.put("jProgressBar.selectionBackground", new ColorUIResource(Color.blue));
jProgressBar.setForeground(Color.blue);
 jProgressBar.setValue(count);


//UIManager.put("jProgressBar.background",Color.YELLOW);


                if (jProgressBar.getValue()<100)
        {
        jProgressBar.setValue(jProgressBar.getValue() + 0);
        }
                     if (jProgressBar.getValue() >= 100)
        {
             t.stop();
         Jhome a1 = new Jhome();
        setVisible(false);
        a1.setVisible(true);
        }
                
            }
        });
        t.start();   
   }
      
               
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jProgressBar);
        jProgressBar.setBounds(-4, 534, 800, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/freelancer_home.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
