/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.DAO.classes.SuperAdminDAO;
import freelancer.entities.SuperAdmin;
import java.util.ArrayList;

/**
 *
 * @author ASUS
 */
public class Superadmin_gererauhtentification extends javax.swing.JFrame {
ArrayList<SuperAdmin> A_SuperAdmin;
  String pseudo;
    /**
     * Creates new form Superadmin_gererauhtentification
     */
    public Superadmin_gererauhtentification(String pseudo) {
        initComponents();
        setTitle("SuperAdmin Logins");
    setSize(800,600);
    setResizable(false);this.setLocationRelativeTo(null);
        this.pseudo=pseudo;
        tf_pseudo1.setText(pseudo);
        SuperAdminDAO admin = new  SuperAdminDAO();
        A_SuperAdmin=(ArrayList<SuperAdmin>) admin.DisplayAllSuperAdministrateurs();
        String login="";
        String password="";
        for (SuperAdmin sup : A_SuperAdmin) {
        login=sup.getPseudo();
        password=sup.getPassword();}  
        tf_pseudo.setText(login);
        tf_password.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_password = new javax.swing.JTextField();
        tf_pseudo1 = new javax.swing.JTextField();
        bt_modifier = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(tf_password);
        tf_password.setBounds(300, 340, 205, 31);
        getContentPane().add(tf_pseudo1);
        tf_pseudo1.setBounds(300, 210, 205, 31);

        bt_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifierActionPerformed(evt);
            }
        });
        getContentPane().add(bt_modifier);
        bt_modifier.setBounds(560, 400, 220, 60);

        jLabel9.setText("Interface Superadmin ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 90, 107, 14);

        tf_pseudo.setEditable(false);
        tf_pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pseudoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 110, 123, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 0, 130, 50);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 0, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/SuperAdmin_gererAuthentification.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifierActionPerformed
        SuperAdmin sup = new SuperAdmin(tf_pseudo1.getText(),tf_password.getText());
        SuperAdminDAO supDAO = new SuperAdminDAO();
        supDAO.updateSuperAdministrateur(sup);
     tf_pseudo.setText(tf_pseudo1.getText());
        /* Superadmin_gererauhtentification supau=new Superadmin_gererauhtentification(tf_pseudo1.getText());
        setVisible(false);
        supau.setVisible(true);*/
    }//GEN-LAST:event_bt_modifierActionPerformed

    private void tf_pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pseudoActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Superadmin_profil s = new Superadmin_profil(pseudo);
        setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

bt_modifier.setBorderPainted(false); 
bt_modifier.setContentAreaFilled(false); 
bt_modifier.setFocusPainted(false); 
bt_modifier.setOpaque(false);

jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Superadmin_gererauhtentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Superadmin_gererauhtentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Superadmin_gererauhtentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Superadmin_gererauhtentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_modifier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_pseudo1;
    // End of variables declaration//GEN-END:variables
}
