/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package freelancer.GUI;

import freelancer.dao.classes.AdministrateurDAO;
import freelancer.entities.Administrateur;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Superadmin_ajoutadministrateur extends javax.swing.JFrame {
 public  String pseudo;
 
    /**
     * Creates new form Administrateur
     */
    public Superadmin_ajoutadministrateur(String pseudo) {
        initComponents();
        setTitle("Ajout D'un Administrateur");
    setSize(800,600);
    setResizable(false);
       this.pseudo=pseudo;
        tf_pseudo.setText(pseudo);this.setLocationRelativeTo(null);
    }
    

public String getText(){
return tf_pseudo1.getText().toString();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tf_nom = new javax.swing.JTextField();
        tf_prenom = new javax.swing.JTextField();
        tf_pays = new javax.swing.JTextField();
        tf_ville = new javax.swing.JTextField();
        tf_pseudo1 = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        tf_mail = new javax.swing.JTextField();
        bt_valider = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel9.setText("Interface Superadmin ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 90, 107, 14);

        tf_pseudo.setEditable(false);
        tf_pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pseudoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pseudo);
        tf_pseudo.setBounds(90, 110, 123, 20);

        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(670, 0, 120, 50);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 0, 50, 50);
        getContentPane().add(tf_nom);
        tf_nom.setBounds(140, 160, 240, 30);
        getContentPane().add(tf_prenom);
        tf_prenom.setBounds(140, 230, 240, 30);
        getContentPane().add(tf_pays);
        tf_pays.setBounds(140, 290, 240, 30);
        getContentPane().add(tf_ville);
        tf_ville.setBounds(140, 350, 240, 30);

        tf_pseudo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pseudo1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pseudo1);
        tf_pseudo1.setBounds(140, 420, 240, 30);
        getContentPane().add(tf_password);
        tf_password.setBounds(140, 480, 240, 30);
        getContentPane().add(tf_mail);
        tf_mail.setBounds(140, 540, 240, 30);

        bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_validerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_valider);
        bt_valider.setBounds(550, 400, 220, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/freelancer/Images/SuperAdmin_ajouterAdmin.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void tf_pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pseudoActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        Jhome a = new Jhome();
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Superadmin_profil s = new Superadmin_profil(pseudo);
        setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_validerActionPerformed
       /* Administrateur  ad = new Administrateur(tf_nom.getText(),tf_prenom.getText(),tf_pays.getText(),tf_ville.getText()
            ,tf_pseudo1.getText(),tf_password.getText(),tf_mail.getText());
        AdministrateurDAO adDAO = new AdministrateurDAO();
        adDAO.insertAdministrateur(ad,ad.getPseudo());
        Superadmin_gereradministrateur a1 = new Superadmin_gereradministrateur(pseudo);
        setVisible(false);//Masquer la JFrame actuelle
        a1.setVisible(true);//Afficher la JFrame Résultat r1*/
         Administrateur  ad = new Administrateur(tf_nom.getText(),tf_prenom.getText(),tf_pays.getText(),tf_ville.getText()
         ,tf_pseudo1.getText(),tf_password.getText(),tf_mail.getText());
      if(tf_nom.getText().length() ==0)  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Nom !!","Message",JOptionPane.ERROR_MESSAGE);
   }else 
 if(tf_prenom.getText().length() ==0)  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Prenom !!","Message",JOptionPane.ERROR_MESSAGE);
  }else
 if(tf_pays.getText().length() ==0)  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Pays !!","Message",JOptionPane.ERROR_MESSAGE);
  }else

if(tf_ville.getText().length() ==0)  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Ville !!","Message",JOptionPane.ERROR_MESSAGE);
  }else

if(tf_pseudo.getText().length() ==0 )  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Pseudo !!","Message",JOptionPane.ERROR_MESSAGE);
 }else
if(tf_mail.getText().length() ==0 )  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Mail !!","Message",JOptionPane.ERROR_MESSAGE);
}else 
   

if(tf_password.getText().length() ==0)  {
   JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Mot de passe !!","Message",JOptionPane.ERROR_MESSAGE);
  
}
else
 if(tf_mail.getText().matches("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+" )) 
 {
   
    AdministrateurDAO adDAO = new AdministrateurDAO();
      adDAO.insertAdministrateur(ad,ad.getPseudo());
     Superadmin_gereradministrateur a1 = new Superadmin_gereradministrateur(pseudo);
    setVisible(false);//Masquer la JFrame actuelle
    a1.setVisible(true);//Afficher la JFrame Résultat r1
 }
 else { JOptionPane.showMessageDialog(null, "Veuillez vérifier le champ mail !!","Message",JOptionPane.ERROR_MESSAGE);
  
 }
    }//GEN-LAST:event_bt_validerActionPerformed

    private void tf_pseudo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pseudo1ActionPerformed

    }//GEN-LAST:event_tf_pseudo1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    bt_logout.setBorderPainted(false); 
bt_logout.setContentAreaFilled(false); 
bt_logout.setFocusPainted(false); 
bt_logout.setOpaque(false);

  jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);

  bt_valider.setBorderPainted(false); 
bt_valider.setContentAreaFilled(false); 
bt_valider.setFocusPainted(false); 
bt_valider.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Superadmin_ajoutadministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Superadmin_ajoutadministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Superadmin_ajoutadministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Superadmin_ajoutadministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    private javax.swing.JButton bt_valider;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_pays;
    private javax.swing.JTextField tf_prenom;
    private javax.swing.JTextField tf_pseudo;
    public javax.swing.JTextField tf_pseudo1;
    private javax.swing.JTextField tf_ville;
    // End of variables declaration//GEN-END:variables
}
